name: Build Site

on:
  push:
    branches:
      - master

jobs:
          
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Build Site
        uses: chabad360/hugo-actions@master
      - name: remove gh-pages
        run: git branch -d gh-pages
      - name: update gh-pages
        run: git subtree push --prefix  public origin gh-pages
