name: Build Site

on:
  push:
    branches:
      - master

jobs:
          
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Build Site
        uses: chabad360/hugo-actions@master
      - name: move to public
        run: cd public
      - name: commit public
        run: git commit -am "update public folder"
      - name: push public
        run: git push  
      
